spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/smartly
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

application.security.jwt.secret-key=4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
application.security.jwt.access-token-expiration=30000000
application.security.jwt.refresh-token-expiration=604800000

spring.mail.host=localhost
spring.mail.port=8025
spring.mail.username=
spring.mail.password=
spring.mail.sender=noreply@smartly.com

server.port=8080
server.ssl.enabled=false
# Disable authentication since it's a local fake server
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

application.front.address.login=http://localhost:4200

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket.company-images=company-images
minio.bucket.company-documents=company-documents
minio.bucket.vehicle-images=vehicle-images